"""
Main module that controls the REST calls for the portal page.
"""
from app import (app, conn_mng)
from app.common import OK_RESPONSE
from flask import jsonify, Response
from shared.constants import PORTAL_ID


@app.route('/api/get_portal_links', methods=['GET'])
def get_portal_links() -> Response:
    """
    Gets the portal links that were generated by the a fabric cron job.

    :return:
    """
    mongo_document = conn_mng.mongo_portal.find_one({"_id": PORTAL_ID})
    if mongo_document is None:
        return OK_RESPONSE

    return jsonify(mongo_document["payload"])
